name: github_user_flutter
description: Github User with Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  json_annotation: ^4.7.0

  flutter_hooks: ^0.18.5+1
  get_it: ^7.2.0
  retrofit: ^3.3.1
  floor: ^1.3.0

  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  ionicons: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
  uses-material-design: true