name: github_user_flutter
version: 1.0.0+1
publish_to: none
description: Github User with Flutter
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  flutter_svg: ^1.1.6
  json_annotation: ^4.7.0
  ionicons: ^0.2.1
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  flutter_test: 
    sdk: flutter

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700

  assets:
    - assets/

  uses-material-design: true

